### ISSUE TITLE
Design new logo linked to name and functionality and change it in the README.md 

### ISSUE THREAD

**Issue by omergulen** [omergulen/copycat#2]

**Comment by sofiarivas** [comment]
Hi @omergulen ! I can help you out with redesigning the logo!

**Comment by omergulen** [comment]
Hey @sofiarivas, I was thinking about making something out of this:
<img src="https://st3.depositphotos.com/4231713/15792/v/1600/depositphotos_157923454-stock-illustration-cat-vector-logo-pet-letter.jpg" />

What do you think?

**Comment by abh1-ja1n** [comment]
Hi @omergulen, I designed a logo.
![copycat_logo](https://user-images.githubusercontent.com/53998159/66777858-c024bd00-eee7-11e9-9b39-2ac87e82aba7.png)
How is it?

**Comment by sofiarivas** [comment]
Here are some of my ideas @omergulen based on the image you uploades 😸 

![Screen Shot 2019-10-14 at 3 04 13 PM](https://user-images.githubusercontent.com/13956453/66779640-4a433600-ee94-11e9-8271-c1408f392bd8.png)
<img width="723" alt="Screen Shot 2019-10-14 at 3 02 00 PM" src="https://user-images.githubusercontent.com/13956453/66779650-50d1ad80-ee94-11e9-986e-d86035857c54.png">

My favorite: 
![copycat](https://user-images.githubusercontent.com/13956453/66779663-5af3ac00-ee94-11e9-8c21-826cd6c7b742.png)

**Comment by tharani29** [comment]
I created the icon yesterday .. it was late, so created pull request today.
<img width="518" alt="Screen Shot 2019-10-15 at 9 45 23 AM" src="https://user-images.githubusercontent.com/703123/66801802-04d84480-ef38-11e9-99f5-f89a27924083.png">

**Comment by omergulen** [comment]
I want to strongly encourage you to use the example I sent you guys :)
